"""initial migration

Revision ID: aa7a360c96dd
Revises: 
Create Date: 2024-03-21 19:21:54.839127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa7a360c96dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('id_author',
               existing_type=sa.CHAR(length=4),
               type_=sa.String(length=4),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_author_fkey', type_='foreignkey')
        batch_op.drop_constraint('books_category_fkey', type_='foreignkey')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('id_category',
               existing_type=sa.CHAR(length=4),
               type_=sa.String(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('id_category',
               existing_type=sa.String(length=4),
               type_=sa.CHAR(length=4),
               existing_nullable=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_foreign_key('books_category_fkey', 'categories', ['category'], ['id_category'])
        batch_op.create_foreign_key('books_author_fkey', 'authors', ['author'], ['id_author'])

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('id_author',
               existing_type=sa.String(length=4),
               type_=sa.CHAR(length=4),
               existing_nullable=False)

    # ### end Alembic commands ###
